apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
        - name: devsecops-demo
          image: 138300868541.dkr.ecr.ap-south-1.amazonaws.com/devsecops-demo:7
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-service
spec:
  type: LoadBalancer
  selector:
    app: devsecops-demo
  ports:
    - port: 80
      targetPort: 8080
